In [1]:
import sys
import os

print("Python:", sys.executable)
print("Working directory:", os.getcwd())

Python: C:\Users\USER\anaconda3\python.exe
Working directory: C:\Users\USER\Documents\DATA SCIENCE\healthcare-risk-system\notebooks

In [2]:
import pandas as pd

print(type(pd))
print("Pandas version:", pd.__version__)

<class 'module'>
Pandas version: 2.3.3

In [3]:
# Then check whether your Synthea data is accessible

from pathlib import Path

data_path = Path("../data/raw/synthea")

print("Data folder exists:", data_path.exists())

if data_path.exists():
    print("CSV files:", len(list(data_path.glob("*.csv"))))

Data folder exists: True
CSV files: 18

In [4]:
# Healthcare Risk System
# Notebook 01 — Data Inventory

print("Healthcare Risk System — Data Inventory")

Healthcare Risk System — Data Inventory

In [5]:
# Import the tools we'll use:

from pathlib import Path
import pandas as pd
import os

DATA_DIR = Path("../data/raw/synthea")

print(f"Data directory: {DATA_DIR.resolve()}")

Data directory: C:\Users\USER\Documents\DATA SCIENCE\healthcare-risk-system\data\raw\synthea

In [6]:
csv_files = sorted(DATA_DIR.glob("*.csv"))

inventory = []

for file in csv_files:
    inventory.append({
        "table": file.stem,
        "file_name": file.name,
        "size_mb": round(file.stat().st_size / (1024 ** 2), 2)
    })

inventory_df = pd.DataFrame(inventory)

inventory_df

                  table                file_name  size_mb
0             allergies            allergies.csv     0.93
1             careplans            careplans.csv     3.65
2                claims               claims.csv   232.03
3   claims_transactions  claims_transactions.csv  2416.34
4            conditions           conditions.csv    31.45
5               devices              devices.csv     7.16
6            encounters           encounters.csv   107.73
7       imaging_studies      imaging_studies.csv   161.68
8         immunizations        immunizations.csv    11.14
9           medications          medications.csv    73.50
10         observations         observations.csv   735.96
11        organizations        organizations.csv     0.18
12             patients             patients.csv     1.65
13    payer_transitions    payer_transitions.csv    34.60
14               payers               payers.csv     0.00
15           procedures           procedures.csv   199.41
16            providers            providers.csv     0.21
17             supplies             supplies.csv    20.29

In [7]:
table_stats = []

for file in csv_files:
    df_sample = pd.read_csv(file, nrows=5)

    with open(file, "rb") as f:
        row_count = sum(1 for _ in f) - 1

    table_stats.append({
        "table": file.stem,
        "rows": row_count,
        "columns": len(df_sample.columns),
        "size_mb": round(file.stat().st_size / (1024 ** 2), 2)
    })

stats_df = pd.DataFrame(table_stats).sort_values("rows", ascending=False)

stats_df

                  table     rows  columns  size_mb
3   claims_transactions  5547678       33  2416.34
10         observations  4355508        9   735.96
15           procedures   932402       10   199.41
2                claims   629678       31   232.03
7       imaging_studies   481554       13   161.68
6            encounters   337227       15   107.73
9           medications   292451       13    73.50
13    payer_transitions   213917        8    34.60
4            conditions   208363        7    31.45
17             supplies   151616        6    20.29
8         immunizations    82882        6    11.14
5               devices    33119        7     7.16
1             careplans    18976        9     3.65
12             patients     5755       28     1.65
0             allergies     5375       15     0.93
11        organizations     1090       12     0.18
16            providers     1090       14     0.21
14               payers       10       22     0.00

In [8]:
# Save the inventory

from pathlib import Path

marts_dir = Path("../data/marts")
marts_dir.mkdir(parents=True, exist_ok=True)

stats_df.to_csv(marts_dir / "table_inventory.csv", index=False)

print("Inventory saved successfully.")

Inventory saved successfully.

In [9]:
# Then verify the file

print((marts_dir / "table_inventory.csv").resolve())
print((marts_dir / "table_inventory.csv").exists())

C:\Users\USER\Documents\DATA SCIENCE\healthcare-risk-system\data\marts\table_inventory.csv
True

In [10]:
stats_df = stats_df.reset_index(drop=True)

stats_df

                  table     rows  columns  size_mb
0   claims_transactions  5547678       33  2416.34
1          observations  4355508        9   735.96
2            procedures   932402       10   199.41
3                claims   629678       31   232.03
4       imaging_studies   481554       13   161.68
5            encounters   337227       15   107.73
6           medications   292451       13    73.50
7     payer_transitions   213917        8    34.60
8            conditions   208363        7    31.45
9              supplies   151616        6    20.29
10        immunizations    82882        6    11.14
11              devices    33119        7     7.16
12            careplans    18976        9     3.65
13             patients     5755       28     1.65
14            allergies     5375       15     0.93
15        organizations     1090       12     0.18
16            providers     1090       14     0.21
17               payers       10       22     0.00

In [11]:
for file in csv_files:
    sample = pd.read_csv(file, nrows=3)
    
    print("=" * 80)
    print(f"TABLE: {file.stem}")
    print(f"SHAPE: {sample.shape}")
    print("COLUMNS:")
    print(list(sample.columns))

================================================================================
TABLE: allergies
SHAPE: (3, 15)
COLUMNS:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'SYSTEM', 'DESCRIPTION', 'TYPE', 'CATEGORY', 'REACTION1', 'DESCRIPTION1', 'SEVERITY1', 'REACTION2', 'DESCRIPTION2', 'SEVERITY2']
================================================================================
TABLE: careplans
SHAPE: (3, 9)
COLUMNS:
['Id', 'START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'REASONCODE', 'REASONDESCRIPTION']
================================================================================
TABLE: claims
SHAPE: (3, 31)
COLUMNS:
['Id', 'PATIENTID', 'PROVIDERID', 'PRIMARYPATIENTINSURANCEID', 'SECONDARYPATIENTINSURANCEID', 'DEPARTMENTID', 'PATIENTDEPARTMENTID', 'DIAGNOSIS1', 'DIAGNOSIS2', 'DIAGNOSIS3', 'DIAGNOSIS4', 'DIAGNOSIS5', 'DIAGNOSIS6', 'DIAGNOSIS7', 'DIAGNOSIS8', 'REFERRINGPROVIDERID', 'APPOINTMENTID', 'CURRENTILLNESSDATE', 'SERVICEDATE', 'SUPERVISINGPROVIDERID', 'STATUS1', 'STATUS2', 'STATUSP', 'OUTSTANDING1', 'OUTSTANDING2', 'OUTSTANDINGP', 'LASTBILLEDDATE1', 'LASTBILLEDDATE2', 'LASTBILLEDDATEP', 'HEALTHCARECLAIMTYPEID1', 'HEALTHCARECLAIMTYPEID2']
================================================================================
TABLE: claims_transactions
SHAPE: (3, 33)
COLUMNS:
['ID', 'CLAIMID', 'CHARGEID', 'PATIENTID', 'TYPE', 'AMOUNT', 'METHOD', 'FROMDATE', 'TODATE', 'PLACEOFSERVICE', 'PROCEDURECODE', 'MODIFIER1', 'MODIFIER2', 'DIAGNOSISREF1', 'DIAGNOSISREF2', 'DIAGNOSISREF3', 'DIAGNOSISREF4', 'UNITS', 'DEPARTMENTID', 'NOTES', 'UNITAMOUNT', 'TRANSFEROUTID', 'TRANSFERTYPE', 'PAYMENTS', 'ADJUSTMENTS', 'TRANSFERS', 'OUTSTANDING', 'APPOINTMENTID', 'LINENOTE', 'PATIENTINSURANCEID', 'FEESCHEDULEID', 'PROVIDERID', 'SUPERVISINGPROVIDERID']
================================================================================
TABLE: conditions
SHAPE: (3, 7)
COLUMNS:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'SYSTEM', 'CODE', 'DESCRIPTION']
================================================================================
TABLE: devices
SHAPE: (3, 7)
COLUMNS:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'UDI']
================================================================================
TABLE: encounters
SHAPE: (3, 15)
COLUMNS:
['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION']
================================================================================
TABLE: imaging_studies
SHAPE: (3, 13)
COLUMNS:
['Id', 'DATE', 'PATIENT', 'ENCOUNTER', 'SERIES_UID', 'BODYSITE_CODE', 'BODYSITE_DESCRIPTION', 'MODALITY_CODE', 'MODALITY_DESCRIPTION', 'INSTANCE_UID', 'SOP_CODE', 'SOP_DESCRIPTION', 'PROCEDURE_CODE']
================================================================================
TABLE: immunizations
SHAPE: (3, 6)
COLUMNS:
['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST']
================================================================================
TABLE: medications
SHAPE: (3, 13)
COLUMNS:
['START', 'STOP', 'PATIENT', 'PAYER', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'PAYER_COVERAGE', 'DISPENSES', 'TOTALCOST', 'REASONCODE', 'REASONDESCRIPTION']
================================================================================
TABLE: observations
SHAPE: (3, 9)
COLUMNS:
['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION', 'VALUE', 'UNITS', 'TYPE']
================================================================================
TABLE: organizations
SHAPE: (3, 12)
COLUMNS:
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'PHONE', 'REVENUE', 'UTILIZATION', 'NPI']
================================================================================
TABLE: patients
SHAPE: (3, 28)
COLUMNS:
['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX', 'FIRST', 'MIDDLE', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'FIPS', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE', 'INCOME']
================================================================================
TABLE: payer_transitions
SHAPE: (3, 8)
COLUMNS:
['PATIENT', 'MEMBERID', 'START_DATE', 'END_DATE', 'PAYER', 'SECONDARY_PAYER', 'PLAN_OWNERSHIP', 'OWNER_NAME']
================================================================================
TABLE: payers
SHAPE: (3, 22)
COLUMNS:
['Id', 'NAME', 'OWNERSHIP', 'ADDRESS', 'CITY', 'STATE_HEADQUARTERED', 'ZIP', 'PHONE', 'AMOUNT_COVERED', 'AMOUNT_UNCOVERED', 'REVENUE', 'COVERED_ENCOUNTERS', 'UNCOVERED_ENCOUNTERS', 'COVERED_MEDICATIONS', 'UNCOVERED_MEDICATIONS', 'COVERED_PROCEDURES', 'UNCOVERED_PROCEDURES', 'COVERED_IMMUNIZATIONS', 'UNCOVERED_IMMUNIZATIONS', 'UNIQUE_CUSTOMERS', 'QOLS_AVG', 'MEMBER_MONTHS']
================================================================================
TABLE: procedures
SHAPE: (3, 10)
COLUMNS:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'SYSTEM', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION']
================================================================================
TABLE: providers
SHAPE: (3, 14)
COLUMNS:
['Id', 'ORGANIZATION', 'NAME', 'GENDER', 'SPECIALITY', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'ENCOUNTERS', 'PROCEDURES', 'NPI']
================================================================================
TABLE: supplies
SHAPE: (3, 6)
COLUMNS:
['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'QUANTITY']